### PR TITLE
refactor: use inversify and simplify code organisation

### LINKED ISSUE #24: Unable to connect to grammarly: auth authentication failed 401 Headers
I noticed that the (excellent!) extension stopped working, checking out the log I noticed the following output (slightly redacted):

```
... 
2020-01-28T11:28:12.815Z grammarly:auth authenticating as <username> {
  accept: 'application/json',
  'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
  'content-type': 'application/json',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) ' +
    'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 ' +
    'Safari/537.36',
  'x-client-type': 'funnel',
  'x-client-version': '1.2.1082',
  'x-container-id': '<some_id>,
  'x-csrf-token': '<some_token>',
  'sec-fetch-site': 'same-site',
  'sec-fetch-mode': 'cors',
  cookie: 'gnar_containrId=some_value; ' +
    'grauth=some_bigger_value; ' +
    'csrf-token=some_token_value'
}

2020-01-28T11:28:13.509Z grammarly:auth authentication failed 401 Headers {
  [Symbol(map)]: [Object: null prototype] {
    date: [ 'Tue, 28 Jan 2020 11:28:13 GMT' ],
    'content-type': [ 'application/json' ],
    'content-length': [ '19' ],
    connection: [ 'close' ],
    'x-frame-options': [ 'DENY' ],
    'x-xss-protection': [ '1; mode=block' ],
    'x-content-type-options': [ 'nosniff' ],
    'content-security-policy': [ "default-src 'none'" ],
    'strict-transport-security': [ 'max-age=31536000' ],
    'cache-control': [ 'max-age=0, no-store, no-cache' ],
    'x-robots-tag': [ 'noindex, nofollow' ]
  }
}
(node:20470) UnhandledPromiseRejectionWarning: Error: Cannot connect to grammarly, no cookie found.
...
```

I made sure that my username and password were correct. Is there anything I can do to diagnose it? Please let me know if I can provide more information

### LINKED ISSUE #25: Mark grammar errors as suggestions
I would like to see my grammar errors as suggestions (underlined in blue) instant of errors (underlined in red), is this possible?

### LINKED ISSUE #30: Connection issue: UnhandledPromiseRejectionWarning
This extension does not work for me at all. 
I have filled in grammarly.username and grammarly.password in settings.
Error message:
2020-02-24T07:49:37.149Z grammarly:host {
  type: 'INIT',
  documentId: 'file:///c%3A/XX.md',
  account: 'public'
}
(node:19612) UnhandledPromiseRejectionWarning: FetchError: request to https://www.grammarly.com/signin failed, reason: getaddrinfo ENOTFOUND www.grammarly.com
    at ClientRequest.<anonymous> (c:\Users\XX\.vscode\extensions\znck.grammarly-0.6.2\out\server.js:15380:11)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
(node:19612) UnhandledPromiseRejectionWarning: FetchError: request to https://www.grammarly.com/signin failed, reason: getaddrinfo ENOTFOUND www.grammarly.com
    at ClientRequest.<anonymous> (c:\Users\XX\.vscode\extensions\znck.grammarly-0.6.2\out\server.js:15380:11)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
(node:19612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:19612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

### LINKED ISSUE #52: GistPad Extension Error
I use the [GistPad](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.gistfs) extension for keeping notes. When opening a markdown file in my Gists library, I get the following error in the vscode developer tools.

Screen Shot 2020-03-17 at 1 25 17 PM

### PR DESCRIPTION
**Pull request by znck**
Fixes #30 - Using cached sessions.
Fixes #52 - Not depending on filesystem. (need confirmation cc @NotMyself)
Fixes #25 - Can configure the severity of grammar errors.
Fixes #24 - Detects captcha prompts.

### CODE REVIEW

**Comment by NotMyself** [comment]
I am getting a new error now with v0.7.1.

```
abstractExtensionService.ts:396 Activating extension 'znck.grammarly' failed: Cannot find module 'inversify'
Require stack:
- /Users/bobby/.vscode/extensions/znck.grammarly-0.7.1/out/extension.js
```

[-1585752790659.log](https://github.com/znck/grammarly/files/4415918/-1585752790659.log)

**Comment by znck** [comment]
Fixed in 0.7.2. Thanks for reporting.

**Comment by NotMyself** [comment]
Can confirm no errors in dev console now. Does not work with GistPad though. I confirmed it works with a md file locally though.

**Comment by NotMyself** [comment]
All issues resolved with 0.9.0.

**Pull request merged**
